server.port: 8082

spring.kafka.streams:
  application-id: wikimedia-stream-processor
  bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVER:localhost:9092}
  properties:
    default.key.serde: org.apache.kafka.common.serialization.Serdes$StringSerde
    default.value.serde: org.apache.kafka.common.serialization.Serdes$StringSerde
